[2025-05-01T14:04:04.591+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.download_dataset manual__2025-05-01T14:03:53.307433+00:00 [queued]>
[2025-05-01T14:04:04.615+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.download_dataset manual__2025-05-01T14:03:53.307433+00:00 [queued]>
[2025-05-01T14:04:04.617+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-01T14:04:04.658+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): download_dataset> on 2025-05-01 14:03:53.307433+00:00
[2025-05-01T14:04:04.696+0000] {standard_task_runner.py:60} INFO - Started process 184 to run task
[2025-05-01T14:04:04.746+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'download_dataset', 'manual__2025-05-01T14:03:53.307433+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmp1vsht7ok']
[2025-05-01T14:04:04.757+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask download_dataset
[2025-05-01T14:04:04.865+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-01T14:04:05.080+0000] {task_command.py:423} INFO - Running <TaskInstance: data_pipeline.download_dataset manual__2025-05-01T14:03:53.307433+00:00 [running]> on host f4e64b717c7c
[2025-05-01T14:04:05.627+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T14:03:53.307433+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-01T14:03:53.307433+00:00'
[2025-05-01T14:04:05.642+0000] {logging_mixin.py:188} INFO - Dataset already exists at /opt/***/datasets/Diabetes/Diabetes.csv
[2025-05-01T14:04:05.649+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-01T14:04:05.722+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=download_dataset, execution_date=20250501T140353, start_date=20250501T140404, end_date=20250501T140405
[2025-05-01T14:04:05.878+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-01T14:04:05.971+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
