[2025-04-30T01:36:50.220+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.download_dataset manual__2025-04-30T01:36:46.521507+00:00 [queued]>
[2025-04-30T01:36:50.250+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.download_dataset manual__2025-04-30T01:36:46.521507+00:00 [queued]>
[2025-04-30T01:36:50.251+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-30T01:36:50.289+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): download_dataset> on 2025-04-30 01:36:46.521507+00:00
[2025-04-30T01:36:50.323+0000] {standard_task_runner.py:60} INFO - Started process 183 to run task
[2025-04-30T01:36:50.354+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'download_dataset', 'manual__2025-04-30T01:36:46.521507+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmp_0ix1huz']
[2025-04-30T01:36:50.362+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask download_dataset
[2025-04-30T01:36:50.421+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-30T01:36:50.581+0000] {task_command.py:423} INFO - Running <TaskInstance: data_pipeline.download_dataset manual__2025-04-30T01:36:46.521507+00:00 [running]> on host c2c1458d457a
[2025-04-30T01:36:50.943+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T01:36:46.521507+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T01:36:46.521507+00:00'
[2025-04-30T01:36:50.955+0000] {logging_mixin.py:188} INFO - Dataset already exists at /opt/***/datasets/Diabetes/Diabetes.csv
[2025-04-30T01:36:50.955+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-30T01:36:51.040+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=download_dataset, execution_date=20250430T013646, start_date=20250430T013650, end_date=20250430T013651
[2025-04-30T01:36:51.188+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-30T01:36:51.356+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
