[2025-05-01T13:53:15.568+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.transform_to_clean manual__2025-05-01T13:52:36.910241+00:00 [queued]>
[2025-05-01T13:53:15.588+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.transform_to_clean manual__2025-05-01T13:52:36.910241+00:00 [queued]>
[2025-05-01T13:53:15.589+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-01T13:53:15.615+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): transform_to_clean> on 2025-05-01 13:52:36.910241+00:00
[2025-05-01T13:53:15.646+0000] {standard_task_runner.py:60} INFO - Started process 237 to run task
[2025-05-01T13:53:15.676+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'transform_to_clean', 'manual__2025-05-01T13:52:36.910241+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmpa1yiji28']
[2025-05-01T13:53:15.687+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask transform_to_clean
[2025-05-01T13:53:15.780+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-01T13:53:15.931+0000] {task_command.py:423} INFO - Running <TaskInstance: data_pipeline.transform_to_clean manual__2025-05-01T13:52:36.910241+00:00 [running]> on host f4e64b717c7c
[2025-05-01T13:53:16.196+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='transform_to_clean' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T13:52:36.910241+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-01T13:52:36.910241+00:00'
[2025-05-01T13:53:16.205+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-01T13:53:16.207+0000] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2025-05-01T13:53:23.634+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_pipeline_dag.py", line 42, in transform_to_clean
    df = df.drop_duplicates().dropna(subset=['race','gender','age', ...])
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 6407, in dropna
    raise KeyError(np.array(subset)[check].tolist())
KeyError: [Ellipsis]
[2025-05-01T13:53:23.659+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline, task_id=transform_to_clean, execution_date=20250501T135236, start_date=20250501T135315, end_date=20250501T135323
[2025-05-01T13:53:23.682+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 35 for task transform_to_clean ([Ellipsis]; 237)
[2025-05-01T13:53:23.841+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-01T13:53:23.895+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
